export const fakeIssueCodeData = [
  {
    id: 'WAUMFAFL8AN208863',
    issue_code: '67046-122',
    issue_description: 'Occlusion L Int Jugular Vein w Extralum Dev, Perc Endo',
    level: 10,
    action_desciption:
      'Migraine, unspecified, without mention of intractable migraine with status migrainosus',
    created_date: '9/14/2020',
    created_by: 'Horatius Mulcock',
    created_by_uid: '1LfQMzBJuDRPM2JZp41gAzvUDJoWs3Yyz7',
  },
  {
    id: 'WUADNAFG9BN262637',
    issue_code: '49349-178',
    issue_description: 'Remove Infusion Dev from Prostate/Seminal Ves, Perc',
    level: 4,
    action_desciption: 'Atheroembolism of lower extremity',
    created_date: '2/3/2020',
    created_by: 'Leoline Castelijn',
    created_by_uid: '1FThmEDDEtNU6BsrUc6es1m8RLURXgUcGW',
  },
  {
    id: '19UUA9F24BA285487',
    issue_code: '50436-3912',
    issue_description: 'Revision of Int Fix in L Metacarpal, Open Approach',
    level: 8,
    action_desciption: 'Benign neoplasm of scalp and skin of neck',
    created_date: '5/19/2020',
    created_by: 'Janette Blazej',
    created_by_uid: '1M8cM6kVq8JBuVnNWfC6uNhDtn6o4WvHWJ',
  },
  {
    id: 'WA1CGAFP1EA856874',
    issue_code: '41163-358',
    issue_description: 'MRI of R Shoulder using Oth Contrast, Unenh, Enhance',
    level: 2,
    action_desciption: 'Benign neoplasm of spinal cord',
    created_date: '5/25/2020',
    created_by: 'Edlin Ducrow',
    created_by_uid: '1LbjHVJgVV66CqgFW8stdiH8CVanBUmtKa',
  },
  {
    id: '4F2CY0C72BK206510',
    issue_code: '58118-1248',
    issue_description: 'Beam Radiation of Kidney using Photons <1 MeV',
    level: 3,
    action_desciption: 'Kaschin-Beck disease, multiple sites',
    created_date: '8/13/2020',
    created_by: 'Karlens Matfield',
    created_by_uid: '1DrTYTFnZzbCVgQh8TVKQsxCUCzcdDYGrk',
  },
  {
    id: 'JTHBP5C2XD5078064',
    issue_code: '58118-2530',
    issue_description:
      'Removal of Neuro Lead from Spinal Cord, Perc Endo Approach',
    level: 9,
    action_desciption: 'Other injury to liver with open wound into cavity',
    created_date: '12/24/2020',
    created_by: 'Briggs McCabe',
    created_by_uid: '1G9Ska5VLTQB6UbLQxDtrejEAz7x1iYeBf',
  },
  {
    id: 'WAUKG98E76A221250',
    issue_code: '41163-121',
    issue_description: 'Excision of Right Mastoid Sinus, Open Approach',
    level: 7,
    action_desciption: 'Dog bite',
    created_date: '7/7/2020',
    created_by: 'Emilie Jerrand',
    created_by_uid: '19JVeb1BN8Qtb13jPf8ZyFPScccB46Y1z5',
  },
  {
    id: 'WBA3B3C52FF200722',
    issue_code: '61715-107',
    issue_description: 'Revision of Bone Stim in Nasal Bone, Extern Approach',
    level: 3,
    action_desciption: 'Injury to inferior vena cava, other',
    created_date: '6/17/2020',
    created_by: 'Cassandre Eathorne',
    created_by_uid: '13RXKkRX6miPH6Sg9PdiazgcjUffmu2PvJ',
  },
  {
    id: 'WBAEH73435B249987',
    issue_code: '51285-446',
    issue_description: 'Supplement Heart with Zooplastic Tissue, Perc Approach',
    level: 7,
    action_desciption: 'Erythema [first degree] of nose (septum)',
    created_date: '5/29/2020',
    created_by: 'Lea Szantho',
    created_by_uid: '1NzcjNhZ8iwuJLjb7VZxb5QQ3V2KXQBAR3',
  },
  {
    id: '2G4WN58CX81111416',
    issue_code: '0944-8503',
    issue_description: 'Beam Radiation of Gallbladder using Electrons',
    level: 9,
    action_desciption:
      'Other specified infectious and parasitic diseases of mother, antepartum condition or complication',
    created_date: '5/4/2020',
    created_by: 'Katherina Mounsie',
    created_by_uid: '1Ae2sbLy6wnSPo8VsebGWkP6PVsUB33iri',
  },
  {
    id: '1G6DN57P490706939',
    issue_code: '49527-989',
    issue_description: 'Bypass R Fem Art to Low Ex Vein w Autol Art, Open',
    level: 1,
    action_desciption:
      'Other and unspecified vaccines and biological substances causing adverse effects in therapeutic use',
    created_date: '2/8/2020',
    created_by: 'Ferdinande Bestall',
    created_by_uid: '1KTmrjMxC1Qyw82AUk4GTie9qJHzq3UfD4',
  },
  {
    id: '5N1AA0ND0EN964696',
    issue_code: '0781-1490',
    issue_description:
      'Drainage of Lower Gingiva with Drain Dev, Open Approach',
    level: 7,
    action_desciption: 'Benign neoplasm of corpus uteri',
    created_date: '1/8/2021',
    created_by: 'Herold Airdrie',
    created_by_uid: '19KMA9A9swhAmTS3Lirc1kxwReJKgLsZzW',
  },
  {
    id: 'KNDJT2A53C7567431',
    issue_code: '0310-0115',
    issue_description: 'Restriction of Bladder Neck, Endo',
    level: 10,
    action_desciption: 'Other preterm infants, unspecified [weight]',
    created_date: '2/16/2020',
    created_by: 'Bucky Felix',
    created_by_uid: '1BdTWqcSYH1zmYyf3iaajxGyjo92KA3Dvk',
  },
  {
    id: '1G4PT5SV3F4664835',
    issue_code: '55154-0126',
    issue_description:
      'Change Other Device in Mouth and Throat, External Approach',
    level: 1,
    action_desciption:
      'Hypertensive heart and chronic kidney disease, malignant, without heart failure and with chronic kidney disease stage V or end stage renal disease',
    created_date: '12/5/2020',
    created_by: 'Beatrice Wharmby',
    created_by_uid: '152U226pCC5vBzXLHHWz7o2FNRFZx8kEzr',
  },
  {
    id: '1N4AB7AP2DN656685',
    issue_code: '42254-310',
    issue_description:
      'Revision of Drain Dev in R Metacarpophal Jt, Open Approach',
    level: 4,
    action_desciption: 'Herpes zoster with unspecified complication',
    created_date: '6/13/2020',
    created_by: 'Desmund Cowcha',
    created_by_uid: '17stJpshkhBXLUzK9BdNRb9oHKxBQZKjvE',
  },
  {
    id: 'JTHBE1BL1FA604939',
    issue_code: '37012-588',
    issue_description:
      'Extirpation of Matter from Cerv Nrv, Perc Endo Approach',
    level: 4,
    action_desciption: 'Acute on chronic diastolic heart failure',
    created_date: '1/17/2021',
    created_by: 'Cassaundra Woollcott',
    created_by_uid: '1JcZdVM1ahYtUdTZkj6EscWL61rZ46nfw',
  },
  {
    id: '2FMPK3J94FB375154',
    issue_code: '0713-0165',
    issue_description: 'Division of Hyoid Bone, Open Approach',
    level: 3,
    action_desciption: 'Disruption of traumatic injury wound repair',
    created_date: '10/27/2020',
    created_by: 'Therese Micklewicz',
    created_by_uid: '17ui8MebA6tEWHEkH49Y4aQSPXG6a4Mk7o',
  },
  {
    id: 'JTEBU5JR9F5027101',
    issue_code: '10191-1458',
    issue_description: 'Extraction of Left Pleura, Perc Endo Approach, Diagn',
    level: 7,
    action_desciption:
      'Bipolar I disorder, most recent episode (or current) mixed, moderate',
    created_date: '7/24/2020',
    created_by: 'Chuck McKendry',
    created_by_uid: '1PDPHzLmRiwME518x2545sTLfnhp8Yxp1X',
  },
  {
    id: 'WAULC58E92A718979',
    issue_code: '0268-0900',
    issue_description:
      'Repair Left Sphenoid Sinus, Percutaneous Endoscopic Approach',
    level: 4,
    action_desciption:
      'Arthropathy associated with other infectious and parasitic diseases, other specified sites',
    created_date: '10/17/2020',
    created_by: 'Stanford Abrahamovitz',
    created_by_uid: '13enFRixBmVWQiHixYm5XfEpEkX8p3a1k2',
  },
  {
    id: '3C4PDCAB6FT283844',
    issue_code: '43742-0163',
    issue_description:
      'Bypass Descending Colon to Desc Colon, Perc Endo Approach',
    level: 9,
    action_desciption: 'Anal fissure',
    created_date: '8/29/2020',
    created_by: 'Sherwood Caslett',
    created_by_uid: '1EzhAG481kPyvXteB6hwiBmg42uPZ4CjCV',
  },
  {
    id: '2HNYD28368H146289',
    issue_code: '68196-190',
    issue_description:
      'Revision of Synth Sub in Cereb Vent, Perc Endo Approach',
    level: 9,
    action_desciption: 'Injury to duodenum, with open wound into cavity',
    created_date: '12/5/2020',
    created_by: 'Olimpia Clapson',
    created_by_uid: '1ExhiSVqfxdJXdEisVVPFaGkj3G7H3suXk',
  },
  {
    id: '5UMBT93567L936138',
    issue_code: '59779-224',
    issue_description:
      'Bypass L Kidney Pelvis to Bladder w Autol Sub, Perc Endo',
    level: 4,
    action_desciption:
      'Nephritis and nephropathy, not specified as acute or chronic, with lesion of membranous glomerulonephritis',
    created_date: '11/24/2020',
    created_by: 'Meade Rime',
    created_by_uid: '12q1jEES9SSaSncVSnyPqGUhtLzHZVbFLn',
  },
  {
    id: 'JHMZF1C41BS473938',
    issue_code: '33261-174',
    issue_description:
      'Dilation of Left Common Iliac Artery, Perc Endo Approach',
    level: 7,
    action_desciption: 'Psychogenic paranoid psychosis',
    created_date: '2/14/2020',
    created_by: 'Marieann McGeagh',
    created_by_uid: '1FZJFraHxPt8ycvAWoBQuDLDtbCJNNvxYc',
  },
  {
    id: 'WDDHF5KB0FB092825',
    issue_code: '65862-468',
    issue_description: 'Occlusion of Carina, Via Natural or Artificial Opening',
    level: 5,
    action_desciption: 'Arthritis due to rubella',
    created_date: '11/6/2020',
    created_by: 'Fredrika Sapey',
    created_by_uid: '1DbFueA8UWPWLJtHZZEa9LWztzEebAXFf8',
  },
  {
    id: 'WBADX1C52CJ157194',
    issue_code: '0268-6790',
    issue_description: 'Wound Mgmt Trmt Integu Head, Neck w Physical Agent',
    level: 9,
    action_desciption: 'Nontraumatic compartment syndrome of upper extremity',
    created_date: '10/5/2020',
    created_by: 'Anica McClenan',
    created_by_uid: '17cKDexjfpGe99wsyCC3wJjwtJDAJSQYw6',
  },
  {
    id: '5N1AN0NW2DN480825',
    issue_code: '52125-039',
    issue_description: 'Ultrasonography of Right Lower Extremity Veins',
    level: 2,
    action_desciption: 'Vitiligo',
    created_date: '5/7/2020',
    created_by: 'Doris Ladloe',
    created_by_uid: '1MsRjwj7nERbf2S7s57R8KMsC4xaZZN9Ln',
  },
  {
    id: 'WAUDF78E85A645891',
    issue_code: '61919-528',
    issue_description:
      'Supplement L Pulm Art with Synth Sub, Perc Endo Approach',
    level: 2,
    action_desciption: 'Open fracture of navicular [scaphoid], foot',
    created_date: '1/24/2020',
    created_by: 'Kimberlyn Lawland',
    created_by_uid: '1NRrXaBZmGHvTEpYtWvW5MR1MWExx1Qvqj',
  },
  {
    id: '5N1AR1NB3BC153348',
    issue_code: '57520-0521',
    issue_description: 'Supplement Nasal Bone with Autol Sub, Perc Approach',
    level: 6,
    action_desciption:
      'Tuberculosis of epididymis, tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]',
    created_date: '9/22/2020',
    created_by: 'Doug Clift',
    created_by_uid: '1LBnh4G7ExgZGbom82H51X4nXqNcNRkK4s',
  },
  {
    id: 'WVGAV3AX6DW055506',
    issue_code: '62756-250',
    issue_description: 'Supplement L Up Extrem Bursa/Lig w Autol Sub, Open',
    level: 2,
    action_desciption:
      'Illegally induced abortion, complicated by embolism, incomplete',
    created_date: '11/10/2020',
    created_by: 'Herb Emmert',
    created_by_uid: '1HfASM7oG6BhiCy35qrijiSez9X5fGM7Hu',
  },
  {
    id: 'WBAKP9C51FD661017',
    issue_code: '36987-2547',
    issue_description:
      'Dilation of L Pulm Vein with Intralum Dev, Open Approach',
    level: 10,
    action_desciption: 'Terrorism involving firearms',
    created_date: '2/10/2020',
    created_by: 'Farrell Pietesch',
    created_by_uid: '1EEpBFEv7CXdv1nYJDcoPVLL7LfbJhzA2f',
  },
];
