export const fakeIssueCodeData = [
  {
    id: 'SCBLE37G73C090854',
    issue_code: '21695-662',
    issue_description:
      'Fluoroscopy of Bilateral Renal Veins using Other Contrast',
    level: 8,
    action_description: 'Stereotypic movement disorder',
    created_date: '11/26/2020',
    created_by: 'Sibelle Bayley',
    created_by_uid: '16H5Qu2tdj6PGzDJYJtyhDvv9d4TKBUXyh',
  },
  {
    id: 'WBAVB13586P469492',
    issue_code: '41250-077',
    issue_description: 'Excision of Right Fallopian Tube, Perc Approach, Diagn',
    level: 2,
    action_description: 'Atypical depressive disorder',
    created_date: '11/30/2020',
    created_by: 'Darci Fludder',
    created_by_uid: '1BDvqDhFSegPK7JbsGYwTuk6ZbairUDa8T',
  },
  {
    id: 'WBA3N3C52FK930399',
    issue_code: '65044-2216',
    issue_description: 'Bypass 3 Cor Art from L Int Mammary w Autol Art, Open',
    level: 10,
    action_description:
      'Suicide and self-inflicted poisoning by unspecified drug or medicinal substance',
    created_date: '2/4/2020',
    created_by: 'Bertram Musterd',
    created_by_uid: '1EQPdzWnWhnB1iqxCGQnNbuRvSovbU1hh8',
  },
  {
    id: '5UXFH0C57AL281609',
    issue_code: '0268-1215',
    issue_description: 'Division of Left Humeral Head, Percutaneous Approach',
    level: 1,
    action_description:
      'Tuberculosis of mother, complicating pregnancy, childbirth, or the puerperium, delivered, with mention of postpartum complication',
    created_date: '7/16/2020',
    created_by: 'Ariadne Wilshire',
    created_by_uid: '1PTb5eKTWQbMtow2mGZZFJ5iye9LEWtxLG',
  },
  {
    id: '19UYA42722A456243',
    issue_code: '98132-141',
    issue_description:
      'Dilate L Int Carotid, Bifurc, w 2 Intralum Dev, Perc Endo',
    level: 10,
    action_description: 'Accident due to excessive cold of man-made origin',
    created_date: '9/12/2020',
    created_by: 'Malia Simko',
    created_by_uid: '16oSQwBvvgC3hKkqkEhcWukpREzSJq4yt5',
  },
  {
    id: 'KMHGC4DE0AU886846',
    issue_code: '58118-5767',
    issue_description: 'Fluoroscopy of Right Foot/Toe Joint',
    level: 4,
    action_description: 'Enthesopathy of elbow, unspecified',
    created_date: '10/20/2020',
    created_by: 'Tudor Rispin',
    created_by_uid: '1E81bKADDoWMiyaEm2aNijpXxxxT4a68st',
  },
  {
    id: 'WAUDL94F05N163430',
    issue_code: '59762-0040',
    issue_description: 'Removal of Spacer from C-thor Jt, Open Approach',
    level: 6,
    action_description: 'Unspecified adverse effect of insulin',
    created_date: '9/7/2020',
    created_by: 'Leon Wofenden',
    created_by_uid: '13ruKBkjUH9mkhtYSL7eH52q1ArXLVVyDW',
  },
  {
    id: 'WAUSF78E38A241506',
    issue_code: '75977-8149',
    issue_description: 'Masking Patterns Assessment',
    level: 9,
    action_description: 'Wandering in diseases classified elsewhere',
    created_date: '6/24/2020',
    created_by: 'Sigvard Eefting',
    created_by_uid: '12MnwhHxUqDsJakcUVWst4Wmqh4C4ZPcTi',
  },
  {
    id: 'JH4CU4F48CC524419',
    issue_code: '43269-807',
    issue_description:
      'Extirpation of Matter from Right Ovary, Perc Endo Approach',
    level: 1,
    action_description: 'Chronic lymphoid leukemia, in remission',
    created_date: '9/11/2020',
    created_by: 'Inge Shedden',
    created_by_uid: '1KFwbXz1xu14AMaTdy3veTUC362M9zzmpr',
  },
  {
    id: '2B3CA8CT0AH971352',
    issue_code: '68428-074',
    issue_description:
      'Drainage of R Glenoid Cav with Drain Dev, Perc Endo Approach',
    level: 9,
    action_description: 'Omphalocele',
    created_date: '9/1/2020',
    created_by: 'Gladi Wytchard',
    created_by_uid: '1QLS4XsbGY1UBJzPq4JYhiuXViFZvrgsns',
  },
  {
    id: 'WBA3A9G50EN797292',
    issue_code: '67457-208',
    issue_description:
      'Drainage of Right Shoulder Bursa and Ligament, Open Approach',
    level: 2,
    action_description: 'Pressure ulcer, upper back',
    created_date: '5/18/2020',
    created_by: 'Darlene Theseira',
    created_by_uid: '17oZCgToRT12QqGkezdwq1bMmibtjycx8S',
  },
  {
    id: '5UMBT93538L850707',
    issue_code: '76439-218',
    issue_description: 'Extraction of Right Foot Vein, Perc Endo Approach',
    level: 5,
    action_description:
      'Closed fracture of base of skull without mention of intra cranial injury, unspecified state of consciousness',
    created_date: '11/5/2020',
    created_by: 'Horatia Kuscha',
    created_by_uid: '16EVAKCm2w7bxfmCtSPqkSwYZTBfBoBoif',
  },
  {
    id: '1FTMF1EW1AK510105',
    issue_code: '0615-6597',
    issue_description: 'Release Right Carpal Joint, Percutaneous Approach',
    level: 5,
    action_description: 'Other specified viral infection',
    created_date: '4/15/2020',
    created_by: 'Yvette Rain',
    created_by_uid: '1AuQPpD5q9qfgx5hQ6tB5N4XqAmCREHodj',
  },
  {
    id: 'JM1CR2W35A0336535',
    issue_code: '10216-3091',
    issue_description: 'Resection of Head and Neck Tendon, Perc Endo Approach',
    level: 6,
    action_description: 'Respiratory arrest',
    created_date: '10/15/2020',
    created_by: 'Northrop Stienton',
    created_by_uid: '16xwX6mfLTNz9UDgjTLi29AS6cFPiDBveY',
  },
  {
    id: 'SCFFDAAEXBG261355',
    issue_code: '42961-009',
    issue_description:
      'Planar Nuclear Medicine Imaging of Abdomen using Iodine 131',
    level: 5,
    action_description: 'Unspecified vascular insufficiency of intestine',
    created_date: '6/30/2020',
    created_by: 'Marve Mardling',
    created_by_uid: '14JhnSc5pbvxUGdKNtunzfE9BUfbGThpVt',
  },
  {
    id: '19UUA9E52CA285016',
    issue_code: '53174-000',
    issue_description:
      'Planar Nuclear Medicine Imaging of Abdomen using Gallium 67',
    level: 8,
    action_description:
      'Other obstetrical pulmonary embolism, delivered, with or without mention of antepartum condition',
    created_date: '6/28/2020',
    created_by: 'Doloritas Boylin',
    created_by_uid: '1GYpPEpvz3iLmyamkezbstzHnk2mDLyuUr',
  },
  {
    id: 'WAUUL78E57A419965',
    issue_code: '33992-0003',
    issue_description:
      'Destruction of Right Ulnar Artery, Percutaneous Approach',
    level: 1,
    action_description: 'Intraventricular hemorrhage, grade II',
    created_date: '5/15/2020',
    created_by: 'Sharyl Colliford',
    created_by_uid: '1Q87nbTFwatqCQdrHiCYVB3RXr6rTCHq1X',
  },
  {
    id: 'WDDUG7JB6EA119491',
    issue_code: '24236-628',
    issue_description:
      'Extirpation of Matter from L Trunk Bursa/Lig, Open Approach',
    level: 9,
    action_description: 'Cystitis in diseases classified elsewhere',
    created_date: '11/15/2020',
    created_by: 'Adamo Raymont',
    created_by_uid: '1C397cZLq9ubpmF7zUczPH87uPWYF72Yzc',
  },
  {
    id: 'WDDGF4HB6ER099975',
    issue_code: '10586-9103',
    issue_description:
      'Replacement of R Radial Art with Synth Sub, Open Approach',
    level: 3,
    action_description: 'Terrorism involving explosion of marine weapons',
    created_date: '6/2/2020',
    created_by: 'Sarajane Heiner',
    created_by_uid: '1KZTa4k3T6H3wUtY8LMp3mGW6RbAy5drE8',
  },
  {
    id: '1FBNE3BL7CD285469',
    issue_code: '64578-0114',
    issue_description: 'Excision of Anus, Percutaneous Approach, Diagnostic',
    level: 4,
    action_description: 'Open wound of palate, complicated',
    created_date: '12/16/2020',
    created_by: 'Putnem Yielding',
    created_by_uid: '1J6VJZfMPRnM7kKJE7GGZEZ9QkUtDAkRx7',
  },
  {
    id: 'KNDPB3A28C7581575',
    issue_code: '0067-6286',
    issue_description: 'Excision of Urethra, Via Natural or Artificial Opening',
    level: 7,
    action_description: 'Marginal corneal ulcer',
    created_date: '4/19/2020',
    created_by: 'Cirstoforo Aldham',
    created_by_uid: '16jXhu13FeeP52kH6gCyPrndAKtZyeFo6T',
  },
  {
    id: 'WDDGF4HB7CF592885',
    issue_code: '0268-6646',
    issue_description: 'Destruction of Left Kidney, Endo',
    level: 3,
    action_description:
      'Gonococcal infection, chronic, of lower genitourinary tract',
    created_date: '10/7/2020',
    created_by: 'Dulcine Kendrick',
    created_by_uid: '1G86EjfaRApFdaDjnWSMCvuVGFKpFtBji7',
  },
  {
    id: 'KNAGM4AD4E5502299',
    issue_code: '59762-1302',
    issue_description: 'Bypass R Radial Art to Low Arm Vein w Autol Art, Open',
    level: 3,
    action_description:
      'Secondary and unspecified malignant neoplasm of intra-abdominal lymph nodes',
    created_date: '2/1/2020',
    created_by: 'Thadeus Babcock',
    created_by_uid: '1CXJDcCaFSLM9wY3zx7kchAdgQfpqiXM21',
  },
  {
    id: '1D7RV1CT0BS109057',
    issue_code: '63354-990',
    issue_description: 'Bypass L Ext Iliac Art to Foot Art w Autol Vn, Open',
    level: 10,
    action_description:
      'Family history of malignant neoplasm of gastrointestinal tract',
    created_date: '8/2/2020',
    created_by: 'Marcellina Oliver-Paull',
    created_by_uid: '1Lda7HwHfkcAcMJofjPuYnWm2SYhTW2kgJ',
  },
  {
    id: '5N1AR1NB0CC611204',
    issue_code: '0113-0622',
    issue_description:
      'Restriction of Anus with Extralum Dev, Perc Endo Approach',
    level: 2,
    action_description: 'Peripheral T cell lymphoma, intrathoracic lymph nodes',
    created_date: '7/23/2020',
    created_by: 'Sibylle Tewkesberry',
    created_by_uid: '19uob6XSicmfE8g1VdTXW2MAKaXBP28CCV',
  },
  {
    id: 'SAJWA6BC3F8161844',
    issue_code: '59779-249',
    issue_description: 'Supplement R Wrist with Autol Sub, Perc Endo Approach',
    level: 1,
    action_description:
      'Peripartum cardiomyopathy, antepartum condition or complication',
    created_date: '7/1/2020',
    created_by: 'Kial Turle',
    created_by_uid: '17UjsGLeP9WHmprnFqgsFj6PB48N9oVZbN',
  },
  {
    id: '3D73M3CL3BG209648',
    issue_code: '68516-4604',
    issue_description: 'Drainage of Bilateral Ureters, Perc Endo Approach',
    level: 10,
    action_description: 'Aneurysm of aorta, specified as syphilitic',
    created_date: '3/15/2020',
    created_by: 'Noby Nolin',
    created_by_uid: '17S9dadyj59xvct4fmbysmoEF2C2GXDk4S',
  },
  {
    id: 'YV4852CT3B1738181',
    issue_code: '35356-748',
    issue_description:
      'Bypass L Com Iliac Art to L Com Ilia w Autol Art, Perc Endo',
    level: 3,
    action_description: 'Adult physical abuse',
    created_date: '4/20/2020',
    created_by: 'Ranna Dudhill',
    created_by_uid: '17cVhoVvyLWpSVxhvia1S8UUiXhMRc8B2L',
  },
  {
    id: 'WBALM7C58AE701629',
    issue_code: '36987-1243',
    issue_description:
      'Occlusion of R Fem Art with Extralum Dev, Open Approach',
    level: 5,
    action_description:
      'Burn [any degree] involving 80-89 percent of body surface with third degree burn, 60-69%',
    created_date: '11/21/2020',
    created_by: 'Curtis Beamish',
    created_by_uid: '1CNRz3oaMWBG7dTivu5WCLYxD42wL74pgx',
  },
  {
    id: 'SCBGH3ZA1EC708500',
    issue_code: '37808-244',
    issue_description: 'Drainage of Left Tarsal, Perc Endo Approach, Diagn',
    level: 10,
    action_description:
      'Multiple closed pelvic fractures with disruption of pelvic circle',
    created_date: '7/25/2020',
    created_by: 'Raimondo Dawtre',
    created_by_uid: '13dum3zYPfBpDHa5E5PXgjCyGLhRnifz3D',
  },
];
